version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: zhiweijz-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: zhiweijz
      POSTGRES_USER: zhiweijz
      POSTGRES_PASSWORD: zhiweijz123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - zhiweijz-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zhiweijz -d zhiweijz"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 后端服务
  backend:
    image: zj591227045/zhiweijz-backend:latest
    container_name: zhiweijz-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://zhiweijz:zhiweijz123@postgres:5432/zhiweijz
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - zhiweijz-network
    depends_on:
      postgres:
        condition: service_healthy

  # 前端服务
  frontend:
    image: zj591227045/zhiweijz-frontend:latest
    container_name: zhiweijz-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DOCKER_ENV: "true"
    networks:
      - zhiweijz-network
    depends_on:
      - backend

  # Nginx 反向代理 (简化版本)
  nginx:
    image: nginx:1.25-alpine
    container_name: zhiweijz-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./config/nginx-simple.conf:/etc/nginx/nginx.conf:ro
    networks:
      - zhiweijz-network
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
    driver: local

networks:
  zhiweijz-network:
    driver: bridge 